version: "3"
services:
  #  Create a service named db.
  employee-management-db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "employee-management"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=employee-management
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=employee-management
    #   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5489:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/employee-management-data